import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { JdSourceType } from '../../../generated/prisma/client.js';
import { AiSuggestionEntity } from '../../ai-suggestions/dto/ai-suggestion.entity.js';

export class ExtractedKeywordsEntity {
  @ApiProperty({ type: [String], example: ['React', 'JavaScript'] })
  matched: string[];

  @ApiProperty({ type: [String], example: ['TypeScript', 'GraphQL'] })
  missing: string[];

  @ApiProperty({ example: 'Good foundation, needs targeted keywords.' })
  summary: string;
}

export class JobDescriptionEntity {
  @ApiProperty()
  id: string;

  @ApiProperty()
  rawText: string;

  @ApiProperty({ enum: JdSourceType })
  sourceType: JdSourceType;

  @ApiPropertyOptional({ description: '0-100 overall match score', example: 76 })
  matchScore: number | null;

  @ApiPropertyOptional({ type: ExtractedKeywordsEntity })
  extractedKeywords: ExtractedKeywordsEntity | null;

  @ApiProperty()
  createdAt: Date;
}

export class JobDescriptionDetailEntity extends JobDescriptionEntity {
  @ApiProperty({
    type: [AiSuggestionEntity],
    description: 'AI suggestions (source=JD_TAILOR) generated by this analysis',
  })
  aiSuggestions: AiSuggestionEntity[];
}
